# -*- coding: utf-8 -*-
"""web-scraping-with-python-using-beautiful-soup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13jQcpDU3WVLA_LBnE2Shy4EeyFenWmZh
"""

#--Web scraping packages
from bs4 import BeautifulSoup
import requests
from csv import writer                                          # to import data to csv

def find_tenders():                                               #defining a function
  html_text = requests.get('https://opentender.eu/start').text    #website used for webscraping 
  soup = BeautifulSoup(html_text, 'html.parser')                  #used for pulling out data from html, etc.
  tenders = soup.find_all('li', class_ = 'portal-link')           #find_all() to find all tags
  with open('tender.csv', 'w', encoding='utf8',newline='') as f: #writes into housing.csv file
    thewriter = writer(f)
    header = ['Country','Tenders',,'Country Info']                                #Column Headers
    thewriter.writerow(header)

    for tender in tenders:
      tender_name = tender.find('a').text.replace(' ','')         #country
      tender_no = tender.find('div').text.replace(' ','')         #no. of tenders
      Country_info = tender.a['href']                             #link to that country
      info=[tender_name, tender_no, Country_info]                
      print(f"Country: {tender_name.strip()}")                    #.strip() used for beautification    
      print(f"Tenders: {tender_no.strip()}")
      print(f"Country_info: {Country_info.strip()}")
      print('')
      thewriter.writerow(info)                                    #writing info for each row

find_tenders()                                                  #calling the function

